### ISSUE TITLE
Code consistency for Javadoc

### ISSUE THREAD

**Issue by dhivesh** [cloudyrock/dimmer-project#59]
- Javadocs in the public interfaces
- Add or remove Authors
- Add Apache License

**Comment by dieppa** [comment]
Classes:

- DimmerConfigException
- DimmerInvocationException
- FeatureInvocation
- DimmerFeatureConfigurable methods
- DimmerBuilder
- FeatureConfigurableBuilder methods: build and buildWithDefaultEnvironment
- FeatureExecutor
- MethodCaller

**Comment by dieppa** [comment]
fixed in pull request #82
